# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import folium, webbrowser #, pandas as pd
import BECKEND
import time, os
regeon = {}
market = {}

file_market = rf"{os.getcwd()}\Data\market.geojson"
file_regions = rf"{os.getcwd()}\Data\regions.geojson"
file_NFZ = rf"{os.getcwd()}\Data\NFZ.geojson"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(757, 913)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(757, 868))
        self.centralwidget.setObjectName("centralwidget")
        self.start_frame = QtWidgets.QFrame(self.centralwidget)
        self.start_frame.setGeometry(QtCore.QRect(10, 10, 721, 341))
        self.start_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.start_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.start_frame.setObjectName("start_frame")
        self.label_2 = QtWidgets.QLabel(self.start_frame)
        self.label_2.setGeometry(QtCore.QRect(370, 170, 221, 31))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.start_frame)
        self.pushButton.setGeometry(QtCore.QRect(0, 220, 171, 31))
        self.pushButton.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(self.start_frame)
        self.label_5.setGeometry(QtCore.QRect(0, 170, 211, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.start_frame)
        self.label_6.setGeometry(QtCore.QRect(210, 170, 121, 31))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.pushButton_4 = QtWidgets.QPushButton(self.start_frame)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 270, 351, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_10 = QtWidgets.QLabel(self.start_frame)
        self.label_10.setGeometry(QtCore.QRect(530, 170, 121, 31))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.pushButton_9 = QtWidgets.QPushButton(self.start_frame)
        self.pushButton_9.setGeometry(QtCore.QRect(180, 220, 171, 31))
        self.pushButton_9.setObjectName("pushButton_9")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.start_frame)
        self.lineEdit_7.setGeometry(QtCore.QRect(280, 0, 71, 41))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_18 = QtWidgets.QLabel(self.start_frame)
        self.label_18.setGeometry(QtCore.QRect(0, 0, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.pushButton_13 = QtWidgets.QPushButton(self.start_frame)
        self.pushButton_13.setGeometry(QtCore.QRect(0, 60, 231, 31))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.start_frame)
        self.pushButton_14.setGeometry(QtCore.QRect(400, 0, 321, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.checkBox = QtWidgets.QCheckBox(self.start_frame)
        self.checkBox.setGeometry(QtCore.QRect(250, 60, 111, 31))
        self.checkBox.setObjectName("checkBox")
        self.pushButton_16 = QtWidgets.QPushButton(self.start_frame)
        self.pushButton_16.setGeometry(QtCore.QRect(540, 110, 181, 31))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_2 = QtWidgets.QPushButton(self.start_frame)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 110, 181, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.start_frame)
        self.pushButton_6.setGeometry(QtCore.QRect(0, 110, 191, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_17 = QtWidgets.QPushButton(self.start_frame)
        self.pushButton_17.setGeometry(QtCore.QRect(380, 220, 321, 31))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_20 = QtWidgets.QPushButton(self.start_frame)
        self.pushButton_20.setGeometry(QtCore.QRect(380, 270, 321, 31))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_18 = QtWidgets.QPushButton(self.start_frame)
        self.pushButton_18.setGeometry(QtCore.QRect(0, 310, 701, 31))
        self.pushButton_18.setObjectName("pushButton_18")
        self.regeons_choseer = QtWidgets.QFrame(self.centralwidget)
        self.regeons_choseer.setEnabled(True)
        self.regeons_choseer.setGeometry(QtCore.QRect(10, 0, 721, 141))
        self.regeons_choseer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.regeons_choseer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.regeons_choseer.setObjectName("regeons_choseer")
        self.comboBox_2 = QtWidgets.QComboBox(self.regeons_choseer)
        self.comboBox_2.setGeometry(QtCore.QRect(0, 10, 721, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.regeons_choseer)
        self.pushButton_5.setGeometry(QtCore.QRect(610, 90, 111, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.Count_people_region = QtWidgets.QLineEdit(self.regeons_choseer)
        self.Count_people_region.setGeometry(QtCore.QRect(520, 60, 201, 21))
        self.Count_people_region.setObjectName("Count_people_region")
        self.label_7 = QtWidgets.QLabel(self.regeons_choseer)
        self.label_7.setGeometry(QtCore.QRect(0, 60, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.pushButton_7 = QtWidgets.QPushButton(self.regeons_choseer)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 90, 111, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.change_center = QtWidgets.QFrame(self.centralwidget)
        self.change_center.setEnabled(True)
        self.change_center.setGeometry(QtCore.QRect(10, 0, 721, 211))
        self.change_center.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.change_center.setFrameShadow(QtWidgets.QFrame.Raised)
        self.change_center.setObjectName("change_center")
        self.label_11 = QtWidgets.QLabel(self.change_center)
        self.label_11.setGeometry(QtCore.QRect(0, 100, 171, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.change_center)
        self.label_12.setGeometry(QtCore.QRect(190, 100, 41, 21))
        self.label_12.setObjectName("label_12")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.change_center)
        self.lineEdit_5.setGeometry(QtCore.QRect(250, 100, 111, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_13 = QtWidgets.QLabel(self.change_center)
        self.label_13.setGeometry(QtCore.QRect(380, 100, 31, 21))
        self.label_13.setObjectName("label_13")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.change_center)
        self.lineEdit_6.setGeometry(QtCore.QRect(450, 100, 101, 21))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_10 = QtWidgets.QPushButton(self.change_center)
        self.pushButton_10.setGeometry(QtCore.QRect(0, 130, 181, 31))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.change_center)
        self.pushButton_11.setGeometry(QtCore.QRect(600, 170, 121, 41))
        self.pushButton_11.setObjectName("pushButton_11")
        self.comboBox_3 = QtWidgets.QComboBox(self.change_center)
        self.comboBox_3.setGeometry(QtCore.QRect(80, 60, 291, 31))
        self.comboBox_3.setObjectName("comboBox_3")
        self.label_14 = QtWidgets.QLabel(self.change_center)
        self.label_14.setGeometry(QtCore.QRect(380, 60, 81, 31))
        self.label_14.setObjectName("label_14")
        self.pushButton_12 = QtWidgets.QPushButton(self.change_center)
        self.pushButton_12.setGeometry(QtCore.QRect(0, 170, 111, 41))
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_15 = QtWidgets.QLabel(self.change_center)
        self.label_15.setGeometry(QtCore.QRect(0, 60, 81, 31))
        self.label_15.setObjectName("label_15")
        self.comboBox_4 = QtWidgets.QComboBox(self.change_center)
        self.comboBox_4.setGeometry(QtCore.QRect(470, 60, 251, 31))
        self.comboBox_4.setObjectName("comboBox_4")
        self.label_17 = QtWidgets.QLabel(self.change_center)
        self.label_17.setGeometry(QtCore.QRect(580, 100, 31, 21))
        self.label_17.setObjectName("label_17")
        self.Score2 = QtWidgets.QComboBox(self.change_center)
        self.Score2.setGeometry(QtCore.QRect(630, 100, 91, 31))
        self.Score2.setObjectName("Score2")
        self.file_changer = QtWidgets.QFrame(self.centralwidget)
        self.file_changer.setGeometry(QtCore.QRect(10, 0, 721, 111))
        self.file_changer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.file_changer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.file_changer.setObjectName("file_changer")
        self.label_20 = QtWidgets.QLabel(self.file_changer)
        self.label_20.setGeometry(QtCore.QRect(0, 40, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.comboBox_5 = QtWidgets.QComboBox(self.file_changer)
        self.comboBox_5.setGeometry(QtCore.QRect(100, 0, 291, 31))
        self.comboBox_5.setObjectName("comboBox_5")
        self.label_21 = QtWidgets.QLabel(self.file_changer)
        self.label_21.setGeometry(QtCore.QRect(0, 0, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.file_changer)
        self.label_22.setGeometry(QtCore.QRect(0, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.comboBox_6 = QtWidgets.QComboBox(self.file_changer)
        self.comboBox_6.setGeometry(QtCore.QRect(100, 40, 291, 31))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_7 = QtWidgets.QComboBox(self.file_changer)
        self.comboBox_7.setGeometry(QtCore.QRect(100, 80, 291, 31))
        self.comboBox_7.setObjectName("comboBox_7")
        self.pushButton_15 = QtWidgets.QPushButton(self.file_changer)
        self.pushButton_15.setGeometry(QtCore.QRect(450, 10, 241, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.add_center = QtWidgets.QFrame(self.centralwidget)
        self.add_center.setEnabled(True)
        self.add_center.setGeometry(QtCore.QRect(10, 10, 721, 121))
        self.add_center.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.add_center.setFrameShadow(QtWidgets.QFrame.Raised)
        self.add_center.setObjectName("add_center")
        self.label = QtWidgets.QLabel(self.add_center)
        self.label.setGeometry(QtCore.QRect(0, 40, 171, 21))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.add_center)
        self.label_3.setGeometry(QtCore.QRect(200, 40, 41, 21))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.add_center)
        self.lineEdit_2.setGeometry(QtCore.QRect(270, 40, 91, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(self.add_center)
        self.label_4.setGeometry(QtCore.QRect(370, 40, 31, 21))
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.add_center)
        self.lineEdit_3.setGeometry(QtCore.QRect(440, 40, 101, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.add_center)
        self.pushButton_3.setGeometry(QtCore.QRect(600, 80, 121, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.comboBox = QtWidgets.QComboBox(self.add_center)
        self.comboBox.setGeometry(QtCore.QRect(80, 0, 291, 31))
        self.comboBox.setObjectName("comboBox")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.add_center)
        self.lineEdit_4.setGeometry(QtCore.QRect(470, 0, 251, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_8 = QtWidgets.QLabel(self.add_center)
        self.label_8.setGeometry(QtCore.QRect(380, 0, 81, 31))
        self.label_8.setObjectName("label_8")
        self.pushButton_8 = QtWidgets.QPushButton(self.add_center)
        self.pushButton_8.setGeometry(QtCore.QRect(0, 70, 111, 41))
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_9 = QtWidgets.QLabel(self.add_center)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 81, 31))
        self.label_9.setObjectName("label_9")
        self.label_16 = QtWidgets.QLabel(self.add_center)
        self.label_16.setGeometry(QtCore.QRect(570, 40, 31, 21))
        self.label_16.setObjectName("label_16")
        self.Score1 = QtWidgets.QComboBox(self.add_center)
        self.Score1.setGeometry(QtCore.QRect(630, 40, 91, 31))
        self.Score1.setObjectName("Score1")
        self.file_to_open_choser = QtWidgets.QFrame(self.centralwidget)
        self.file_to_open_choser.setGeometry(QtCore.QRect(0, 0, 721, 111))
        self.file_to_open_choser.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.file_to_open_choser.setFrameShadow(QtWidgets.QFrame.Raised)
        self.file_to_open_choser.setObjectName("file_to_open_choser")
        self.comboBox_11 = QtWidgets.QComboBox(self.file_to_open_choser)
        self.comboBox_11.setGeometry(QtCore.QRect(130, 10, 291, 41))
        self.comboBox_11.setObjectName("comboBox_11")
        self.label_27 = QtWidgets.QLabel(self.file_to_open_choser)
        self.label_27.setGeometry(QtCore.QRect(0, 10, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.pushButton_19 = QtWidgets.QPushButton(self.file_to_open_choser)
        self.pushButton_19.setGeometry(QtCore.QRect(450, 10, 241, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_21 = QtWidgets.QPushButton(self.file_to_open_choser)
        self.pushButton_21.setGeometry(QtCore.QRect(0, 70, 131, 41))
        self.pushButton_21.setObjectName("pushButton_21")
        self.R_Editor = QtWidgets.QFrame(self.centralwidget)
        self.R_Editor.setGeometry(QtCore.QRect(10, 0, 711, 541))
        self.R_Editor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.R_Editor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.R_Editor.setObjectName("R_Editor")
        self.label_19 = QtWidgets.QLabel(self.R_Editor)
        self.label_19.setGeometry(QtCore.QRect(0, 0, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_23 = QtWidgets.QLabel(self.R_Editor)
        self.label_23.setGeometry(QtCore.QRect(0, 300, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.R_Editor)
        self.label_24.setGeometry(QtCore.QRect(0, 400, 481, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.R_Editor)
        self.label_25.setGeometry(QtCore.QRect(0, 30, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.R_Editor)
        self.label_26.setGeometry(QtCore.QRect(0, 120, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_28 = QtWidgets.QLabel(self.R_Editor)
        self.label_28.setGeometry(QtCore.QRect(0, 210, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.pushButton_22 = QtWidgets.QPushButton(self.R_Editor)
        self.pushButton_22.setGeometry(QtCore.QRect(600, 460, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setObjectName("pushButton_22")
        self.lineEdit = QtWidgets.QLineEdit(self.R_Editor)
        self.lineEdit.setGeometry(QtCore.QRect(202, 460, 141, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_29 = QtWidgets.QLabel(self.R_Editor)
        self.label_29.setGeometry(QtCore.QRect(0, 460, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.R_Editor)
        self.lineEdit_8.setGeometry(QtCore.QRect(500, 460, 91, 31))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_30 = QtWidgets.QLabel(self.R_Editor)
        self.label_30.setGeometry(QtCore.QRect(350, 460, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.pushButton_23 = QtWidgets.QPushButton(self.R_Editor)
        self.pushButton_23.setGeometry(QtCore.QRect(0, 510, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.R_Editor)
        self.pushButton_24.setGeometry(QtCore.QRect(160, 70, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setObjectName("pushButton_24")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.R_Editor)
        self.lineEdit_9.setGeometry(QtCore.QRect(0, 70, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.R_Editor)
        self.lineEdit_10.setGeometry(QtCore.QRect(0, 160, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.pushButton_25 = QtWidgets.QPushButton(self.R_Editor)
        self.pushButton_25.setGeometry(QtCore.QRect(160, 160, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setObjectName("pushButton_25")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.R_Editor)
        self.lineEdit_11.setGeometry(QtCore.QRect(0, 260, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.pushButton_26 = QtWidgets.QPushButton(self.R_Editor)
        self.pushButton_26.setGeometry(QtCore.QRect(160, 260, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setObjectName("pushButton_26")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.R_Editor)
        self.lineEdit_12.setGeometry(QtCore.QRect(0, 350, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.pushButton_27 = QtWidgets.QPushButton(self.R_Editor)
        self.pushButton_27.setGeometry(QtCore.QRect(160, 350, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.R_Editor)
        self.pushButton_28.setGeometry(QtCore.QRect(240, 510, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setObjectName("pushButton_28")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 757, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Центры активности"))
        self.pushButton.setText(_translate("MainWindow", "Добавить ЦА"))
        self.label_5.setText(_translate("MainWindow", "Населенность(общая)"))
        self.pushButton_4.setText(_translate("MainWindow", "Изменить населенность регионов"))
        self.pushButton_9.setText(_translate("MainWindow", "Изменить ЦА"))
        self.lineEdit_7.setText(_translate("MainWindow", "0"))
        self.label_18.setText(_translate("MainWindow", "Количество почтамтов"))
        self.pushButton_13.setText(_translate("MainWindow", "Select input files"))
        self.pushButton_14.setText(_translate("MainWindow", "Start"))
        self.checkBox.setText(_translate("MainWindow", "Not Update"))
        self.pushButton_16.setText(_translate("MainWindow", "Edit NFZ as .GeoJson"))
        self.pushButton_2.setText(_translate("MainWindow", "Edit CA as .GeoJson"))
        self.pushButton_6.setText(_translate("MainWindow", "Edit regions as .GeoJson"))
        self.pushButton_17.setText(_translate("MainWindow", "See critical values"))
        self.pushButton_20.setText(_translate("MainWindow", "Open ready result"))
        self.pushButton_18.setText(_translate("MainWindow", "coefficients"))
        self.pushButton_5.setText(_translate("MainWindow", "Apply"))
        self.Count_people_region.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "Количество людей в регионе"))
        self.pushButton_7.setText(_translate("MainWindow", "Close"))
        self.label_11.setText(_translate("MainWindow", "Координаты"))
        self.label_12.setText(_translate("MainWindow", "Х:"))
        self.lineEdit_5.setText(_translate("MainWindow", "0"))
        self.label_13.setText(_translate("MainWindow", "Y:"))
        self.lineEdit_6.setText(_translate("MainWindow", "0"))
        self.pushButton_10.setText(_translate("MainWindow", "Edit as .GeoJson"))
        self.pushButton_11.setText(_translate("MainWindow", "Change"))
        self.label_14.setText(_translate("MainWindow", "Name"))
        self.pushButton_12.setText(_translate("MainWindow", "Close"))
        self.label_15.setText(_translate("MainWindow", "Type"))
        self.label_17.setText(_translate("MainWindow", "Score"))
        self.label_20.setText(_translate("MainWindow", "ЦА"))
        self.label_21.setText(_translate("MainWindow", "РЕГИОНЫ"))
        self.label_22.setText(_translate("MainWindow", "NFZ"))
        self.pushButton_15.setText(_translate("MainWindow", "APPLY"))
        self.label.setText(_translate("MainWindow", "Координаты"))
        self.label_3.setText(_translate("MainWindow", "Х:"))
        self.lineEdit_2.setText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "Y:"))
        self.lineEdit_3.setText(_translate("MainWindow", "0"))
        self.pushButton_3.setText(_translate("MainWindow", "Apply"))
        self.lineEdit_4.setText(_translate("MainWindow", "Name"))
        self.label_8.setText(_translate("MainWindow", "Name"))
        self.pushButton_8.setText(_translate("MainWindow", "Close"))
        self.label_9.setText(_translate("MainWindow", "Type"))
        self.label_16.setText(_translate("MainWindow", "Score"))
        self.label_27.setText(_translate("MainWindow", "DATA"))
        self.pushButton_19.setText(_translate("MainWindow", "APPLY"))
        self.pushButton_21.setText(_translate("MainWindow", "Close"))
        self.label_19.setText(_translate("MainWindow", "R"))
        self.label_23.setText(_translate("MainWindow", "груз за день от одного человека(0.08 Moskow)"))
        self.label_24.setText(_translate("MainWindow", "типы центров активности(только английский)"))
        self.label_25.setText(_translate("MainWindow", "радиус в котором вокруг почтамта обрабатывается Населенность"))
        self.label_26.setText(_translate("MainWindow", "радиус в котором вокруг почтамта обрабатывается Центры Активности"))
        self.label_28.setText(_translate("MainWindow", "радиус в котором Центры Активности собирают часть Населенности на себя"))
        self.pushButton_22.setText(_translate("MainWindow", "Add"))
        self.label_29.setText(_translate("MainWindow", "Name"))
        self.label_30.setText(_translate("MainWindow", "coficient"))
        self.pushButton_23.setText(_translate("MainWindow", "Close"))
        self.pushButton_24.setText(_translate("MainWindow", "Change"))
        self.pushButton_25.setText(_translate("MainWindow", "Change"))
        self.pushButton_26.setText(_translate("MainWindow", "Change"))
        self.pushButton_27.setText(_translate("MainWindow", "Change"))
        self.pushButton_28.setText(_translate("MainWindow", "restore all to default"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        """Main Code"""
#----------------------------------------------------------------
        """BECKENDSTART"""

        global regeon, market       # name:[(x, y), population]      name:[(x, y), type ,raiting]
        global file_market, file_regions, file_NFZ
        regeon, market = BECKEND.Update(file_market, file_regions, file_NFZ)

#----------------------------------------------------------------
        self.label_6.setText(str(sum(list(int(regeon[i][1]) for i in regeon.keys()))))
        self.label_10.setText(str(len(list(market.keys()))))
        self.comboBox_4.addItems(list(i for i in market.keys()))
        self.Score1.addItems(list(str(i) for i in range(0, 11)))
        self.Score2.addItems(list(str(i) for i in range(0, 11)))

#-------------------------------------------------
        self.checkBox.setToolTip("if you alredy start your programm with the same input")
        self.comboBox_5.addItems(BECKEND.work_files())
        self.comboBox_6.addItems(BECKEND.work_files())
        self.comboBox_7.addItems(BECKEND.work_files())
        self.comboBox_11.addItems(BECKEND.file_to_open())
        self.pushButton_10.clicked.connect(self.open_CA_geojason)
        self.pushButton_6.clicked.connect(self.open_regions_geojason)
        self.pushButton_2.clicked.connect(self.open_CA_geojason)
        self.pushButton_16.clicked.connect(self.open_NFZ_geojason)
        self.pushButton_13.clicked.connect(self.open_files_changer)
        self.pushButton_15.clicked.connect(self.change_inputfile)
        self.comboBox.addItems(list(BECKEND.typekof.keys()))
        self.comboBox_3.addItems(list(BECKEND.typekof.keys()))
        self.comboBox_2.addItems(list(regeon.keys()))
        self.pushButton_8.clicked.connect(self.close_adder)
        self.pushButton_7.clicked.connect(self.close_chenger)
        self.comboBox_2.activated[str].connect(self.update_peoaple_per_region)
        self.comboBox_4.activated[str].connect(self.update_market_info)
        self.pushButton.clicked.connect(self.show_adder)
        self.pushButton_14.clicked.connect(self.Start)
        self.pushButton_3.clicked.connect(self.add_point)
        self.pushButton_4.clicked.connect(self.show_chenger)
        self.pushButton_5.clicked.connect(self.change_regeon_population)
        self.pushButton_9.clicked.connect(self.show_chenger_center)
        self.pushButton_12.clicked.connect(self.close_changer_center)
        self.pushButton_11.clicked.connect(self.change_market)
        self.pushButton_17.clicked.connect(self.show_crit_val)
        self.pushButton_19.clicked.connect(self.show_upload_result)
        self.pushButton_20.clicked.connect(self.open_choser_file_to_open)
        self.pushButton_21.clicked.connect(self.close_choser_file_to_open)
        self.pushButton_18.clicked.connect(self.open_r_editor)
        self.pushButton_23.clicked.connect(self.close_r_editor)
        self.pushButton_28.clicked.connect(self.restore)
        self.pushButton_24.clicked.connect(self.change_reg_kof)
        self.pushButton_25.clicked.connect(self.change_market_kof)
        self.pushButton_26.clicked.connect(self.change_market_build_kof)
        self.pushButton_27.clicked.connect(self.change_cargo_per_peple)
        self.pushButton_22.clicked.connect(self.change_market_types)
        self.file_changer.hide()
        self.add_center.hide()
        self.change_center.hide()
        self.regeons_choseer.hide()
        self.file_to_open_choser.hide()
        self.R_Editor.hide()

#-----------------------------------------------------------------
    def open_files_changer(self):
        global file_market, file_NFZ, file_regions
        a, b, c = file_market, file_NFZ, file_regions
        d = "\\Data\\"
        a, b, c = a.replace(os.getcwd() + d, ""), b.replace(os.getcwd()+d, ""), c.replace(os.getcwd()+d, "")
        print(a, b, c)
        self.comboBox_5.setCurrentText(c)
        self.comboBox_6.setCurrentText(a)
        self.comboBox_7.setCurrentText(b)
        self.start_frame.hide()
        self.file_changer.show()

    def open_r_editor(self):
        self.lineEdit_9.setText(str(round(BECKEND.R["regeon"] * 111, 5)))
        self.lineEdit_10.setText(str(round(BECKEND.R["market"] * 111, 5)))
        self.lineEdit_11.setText(str(round(BECKEND.R["actcenter_builder"] * 111, 5)))
        self.lineEdit_12.setText(str(round(BECKEND.cargo_per_peeple["Default"], 5)))
        self.R_Editor.show()
        self.start_frame.hide()

    def close_r_editor(self):
        self.R_Editor.hide()
        self.start_frame.show()
        print(f"R:{BECKEND.R}\ncargo_per_peeple:{BECKEND.cargo_per_peeple}\n types:{BECKEND.typekof}")

    def update_market_info(self, text):
        self.comboBox_3.setCurrentText(market[text][1])
        self.Score2.setCurrentText(str(market[text][2]))
        self.lineEdit_5.setText(str(market[text][0][0]))
        self.lineEdit_6.setText(str(market[text][0][1]))

    def update_peoaple_per_region(self, text):
        global regeon
        self.Count_people_region.setText(regeon[text][1])

    def show_adder(self):
        self.start_frame.hide()
        self.add_center.show()

    def show_chenger_center(self):
        self.start_frame.hide()
        self.change_center.show()

    def close_changer_center(self):
        self.start_frame.show()
        self.change_center.hide()

    def show_chenger(self):
        self.start_frame.hide()
        self.regeons_choseer.show()
        self.Count_people_region.setText(regeon[self.comboBox_2.currentText()][1])

    def close_adder(self):
        self.start_frame.show()
        self.add_center.hide()

    def close_chenger(self):
        self.start_frame.show()
        self.regeons_choseer.hide()
#------------------------------------------------------------------
    def change_reg_kof(self):
        try:
            new_r = float(self.lineEdit_9.text()) / 111
            BECKEND.R["region"] = round(new_r, 5)
            print(f"R:{BECKEND.R}\ncargo_per_peeple:{BECKEND.cargo_per_peeple}\n types:{BECKEND.typekof}")
        except:
            Errore_dialog("кофициент радиуса региона должен быть float")

    def change_market_kof(self):
        try:
            new_r = float(self.lineEdit_10.text()) / 111
            BECKEND.R["market"] = round(new_r, 5)
            print(f"R:{BECKEND.R}\ncargo_per_peeple:{BECKEND.cargo_per_peeple}\n types:{BECKEND.typekof}")
        except:
            Errore_dialog("кофициент центра активности должен быть float")

    def change_market_build_kof(self):
        try:
            new_r = float(self.lineEdit_11.text()) / 111
            BECKEND.R["actcenter_builder"] = round(new_r, 5)
            print(f"R:{BECKEND.R}\ncargo_per_peeple:{BECKEND.cargo_per_peeple}\n types:{BECKEND.typekof}")
        except:
            Errore_dialog("кофициент создания центра активности должен быть float")

    def change_cargo_per_peple(self):
        try:
            new_r = float(self.lineEdit_12.text())
            BECKEND.cargo_per_peeple["Default"] = round(new_r, 5)
            print(f"R:{BECKEND.R}\ncargo_per_peeple:{BECKEND.cargo_per_peeple}\n types:{BECKEND.typekof}")
        except:
            Errore_dialog("кофициент отправок посылок с чловека за день должен быть float")

    def change_market_types(self):
        try:
            new_type = str(self.lineEdit.text())
            new_k = float(self.lineEdit_8.text())
        except:
            Errore_dialog("странный тип или кофицент типа")
            return
        if 0 <= new_k <= 1:
            if new_type not in BECKEND.typekof.keys():
                BECKEND.typekof.update({new_type: new_k})
                print(f"R:{BECKEND.R}\ncargo_per_peeple:{BECKEND.cargo_per_peeple}\n types:{BECKEND.typekof}")
            else:
                Errore_dialog("такой тип уже есть")
        else:
            Errore_dialog("кофицент должен быть от 0 до 1")

    def change_market(self):
        self.close_changer_center()
        BECKEND.change_actceter(self.comboBox_4.currentText(), self.Score2.currentText(), self.lineEdit_5.text(), self.lineEdit_6.text(), self.comboBox_3.currentText())

    def restore(self):
        BECKEND.R = {"regeon": 0.009, "market": 0.005, "actcenter_builder": 0.015}
        BECKEND.cargo_per_peeple = {"Default": 0.08}
        BECKEND.typekof = {"Default": 0.0, "market": 0.4, "BC": 0.5, "SHOPPINGCENTER": 0.5, "Market": 0.5, "HyperMarket": 0.5, "Businesscenter": 0.4}
        self.close_r_editor()

    def add_point(self):
        global file_market, file_regions, file_NFZ
        a, b = None, None
        global market
        try:
            a = float(self.lineEdit_2.text())
            b = float(self.lineEdit_3.text())
            if a is not None and b is not None:
                self.close_adder()
                BECKEND.add_center_activity(self.lineEdit_4.text(),self.Score1.currentText(), a, b, self.comboBox.currentText())
                market = BECKEND.Update(file_market, file_regions, file_NFZ)[1]
            else:
                Errore_dialog("No values of coordinats")
        except:
            Errore_dialog("кординаты должны быть float(например 0.002103)")

    def change_regeon_population(self):
        global regeon
        global file_market, file_regions, file_NFZ
        BECKEND.Update_region_population(self.comboBox_2.currentText(), self.Count_people_region.text())
        regeon = BECKEND.Update(file_market, file_regions, file_NFZ)[0]
        self.close_chenger()

    def show_crit_val(self):
        print(f"[+]critical values pochtamt per day is {BECKEND.find_critical_value(True)}")

    def open_CA_geojason(self):
        global file_market
        BECKEND.Open_geojason(file_market)

    def open_regions_geojason(self):
        global file_regions
        BECKEND.Open_geojason(file_regions)

    def open_NFZ_geojason(self):
        global file_NFZ
        BECKEND.Open_geojason(file_NFZ)

    def change_inputfile(self):
        global file_market, file_regions, file_NFZ
        global regeon, market
        file_regions = fr"{os.getcwd()}/Data/{self.comboBox_5.currentText()}"
        file_market = fr"{os.getcwd()}/Data/{self.comboBox_6.currentText()}"
        file_NFZ = fr"{os.getcwd()}\Data\{self.comboBox_7.currentText()}"
        print(file_market, file_regions, file_NFZ)
        regeon, market = BECKEND.Update(file_market, file_regions, file_NFZ)
        self.comboBox_4.clear()
        self.comboBox_4.addItems(list(i for i in market.keys()))
        self.comboBox_2.clear()
        self.comboBox_2.addItems(list(regeon.keys()))
        self.start_frame.show()
        self.file_changer.hide()

    def open_choser_file_to_open(self):
        self.start_frame.hide()
        self.file_to_open_choser.show()

    def show_upload_result(self):
        self.close_choser_file_to_open()
        file = fr"{os.getcwd()}/Data/{self.comboBox_11.currentText()}"
        BECKEND.open_result(file)

    def close_choser_file_to_open(self):
        self.start_frame.show()
        self.file_to_open_choser.hide()


    def Start(self):
        print(f"________________________{self.lineEdit_7.text()}")
        try:
            int(self.lineEdit_7.text())
        except:
            Errore_dialog("pochtampt count  mast be int")
            return
        if int(self.lineEdit_7.text()) == 0:
            Errore_dialog("pochtampt count is 0. Maybe it's mistake")
            return
        BECKEND.see_result(int(self.lineEdit_7.text()), self.checkBox.isTristate())
        # self.progressBar.setVisible(True)
        # self.pushButton_14.setVisible(False)
        # self.progressBar.setRange(1, count)
        #self.progressBar.setValue(0)

    # def upd_progressBar(self, progress):
    #     if self.progressBar.maximum() == progress:
    #         self.progressBar.setVisible(False)
    #         self.pushButton_14.setVisible(True)
    #         return
    #     self.progressBar.setValue(progress)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())